version: 2
job_defaults: &defaults
  docker:
    - image: circleci/clojure:lein-2.8.1

jobs:
  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - run:
        command: |
          sudo apt-get install make
          make test
  integration-tests:
    <<: *defaults
    steps:
      - checkout
      - run:
        command: |
          sudo apt-get install make
          make test-integration
workflows:
  version: 2
  test:
    jobs:
      - unit-tests
      - integration-tests
